### PR TITLE
Convert intrinsic function tags to Fn:: format

### LINKED ISSUE #29: Can't use !-style intrinsic functions in local YAML templates
Cuffsert loads local YAML templates and converts them into JSON before sending them to CloudFormation. If the YAML contains functions like `!Sub` and `!Ref` these will be copied verbatim into the JSON and CloudFormation will not see them as function calls.

### LINKED ISSUE #31: CuffSert::Abort does not implement #validate!
I got this error that probably masked another error:

```
…/gems/2.4.0/gems/cuffsert-0.12.0/lib/cuffsert/main.rb:50:in `run': undefined method `validate!' for #<CuffSert::Abort:0x00007faa28c475c8> (NoMethodError)
```

`CuffSert.determine_action` can return a `CuffSert::Abort`, which isn't an action.

### PR DESCRIPTION
**Pull request by bittrance**
This PR makes it possible to update YAML templates which contains e.g. `!Ref` or `!Sub` by registering Psych handlers for all known CF intrinsic functions. The handlers convert the tags to `Fn::<func>` syntax. The tags cause problems because there is no way to ask Psych not to process them.

It can be argued that we should have handlers which recreates the original tag. The problem is that we minimize the template by dumping it as JSON (regardless of input format) and there is currently no easy way to get Psych to output flow-style YAML (see https://github.com/ruby/psych/issues/281). Given the low size limit for templates and the superior ergonomy of directly uploaded templates, this minimization is an important aspect. Nor is it trivial to figure out if a template is written in JSON or YAML so that we know what format to output. Hence this narrow approach.

Fixes #29 .

### CODE REVIEW

File: lib/cuffsert/yaml-ext.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+module YAML
+  %w[Ref].each do |name|
+    add_domain_type('cuffsert', name) do |tag, value|
+      {name => value}
+    end
+  end
+
+  add_domain_type('cuffsert', 'GetAtt') do |_, value|
+    {'Fn::GetAtt' => value.to_s.split('.')}
```
Comment (iconara) [inline lib/cuffsert/yaml-ext.rb]: `!GetAtt [Distribution, DomainName]` seems to be supported too, although not documented. I can live with not supporting it, but I actually have a template that's using that syntax.

File: lib/cuffsert/yaml-ext.rb [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+  end
+
+  %w[
+    Base64 Cidr FindInMap GetAZs ImportValue Join Select Split Sub Transform
+    And Equals If Not Or
+  ].each do |name|
+    add_domain_type('cuffsert', name) do |tag, value|
+      {['Fn', name].join('::') => value}
```
Comment (iconara) [inline lib/cuffsert/yaml-ext.rb:23]: Does this work with for example

```yaml
Name: !Sub
  - www.${Domain}
  - { Domain: !Ref RootDomainName }
```

(example from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)

i.e. is `value` the list in that case?

File: lib/cuffsert/yaml-ext.rb (hunk 1 above)
Comment (iconara) [reply lib/cuffsert/yaml-ext.rb]: I think it's shorthand for

```yaml
DNSName: !GetAtt
  - Distribution
  - DomainName
```

Comment (bittrance) [reply lib/cuffsert/yaml-ext.rb]: If you say so :) . Supported now.

File: lib/cuffsert/yaml-ext.rb (hunk 2 above)
Comment (bittrance) [reply lib/cuffsert/yaml-ext.rb:23]: Yes, Psych expands nested tags. Added example to illustrate this.

**Review by iconara — APPROVED** [review]
👌
