### PR TITLE
Better presentation of failure

### LINKED ISSUE #6: Exceptions should give non-zero exit code
Currently, we print exception and exit, but we do not set a non-zero exit code. SImply doing exit 1 is good enough for now.

### LINKED ISSUE #32: Successful update rollback should not constitute success
It does not seem reasonable that this is considered successful:
```
Updating stack ze-stack
SgRules[AWS::EC2::SecurityGroupIngress] Add
Continue? [yN]
UPDATE_IN_PROGRESS 18:56:16+0000  ze-stack[Stack] User Initiated
UPDATE_ROLLBACK_IN_PROGRESS 18:56:17+0000  ze-stack[Stack] No export named zeSecurityGroupId found
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS 18:56:22+0000  ze-stack[Stack]
UPDATE_ROLLBACK_COMPLETE 18:56:23+0000  ze-stack[Stack]
Done.
```

### PR DESCRIPTION
**Pull request by bittrance**
- UPDATE_ROLLBACK_COMPLETE is hardly a good state; treat it as a failure
- rxcfclient treats bad states as Rx errors
- present checked errors by their message
- exit with 1 on errors

Fixes #6.
Fixes #32.

### CODE REVIEW

File: lib/cuffsert/presenters.rb [hunk 1]
```diff
@@ -90,7 +101,7 @@ def on_stack_event(event)
       update_resource_states(resource, event)
       @renderer.event(event, resource)
       @renderer.clear
-      @resources.each { |resource| @renderer.resource(resource) }
+      @resources.each { |r| @renderer.resource(r) }
```
Comment (grddev) [inline lib/cuffsert/presenters.rb]: This seems accidental

File: lib/cuffsert/rxcfclient.rb [hunk 2]
```diff
@@ -94,8 +99,15 @@ def record_start_time
     end
 
     def stack_finished?(stack_id, event)
-      event[:physical_resource_id] == stack_id &&
-        FINAL_STATES.include?(event[:resource_status])
+      return false unless event[:physical_resource_id] == stack_id
+      case CuffSert.state_category(event[:resource_status])
+      when :bad
+        raise RxCFError, "Stack #{event.logical_resource_id} finished in state #{event.resource_status}"
```
Comment (grddev) [inline lib/cuffsert/rxcfclient.rb]: Not sure how this all fits together, but won't raising here mean that we risk not processing additional events?

Comment (bittrance) [reply lib/cuffsert/rxcfclient.rb]: That's true, good catch. Concretely, cleanup-events will show up after the stack event. Not sure if you can get cleanup-events after a failure, but let's not take that chance.

Comment (bittrance) [reply lib/cuffsert/rxcfclient.rb]: Fixed.

File: lib/cuffsert/presenters.rb (hunk 1 above)
Comment (bittrance) [reply lib/cuffsert/presenters.rb]: Fixed.

File: lib/cuffsert/presenters.rb [hunk 3]
```diff
@@ -76,6 +77,16 @@ def on_event(event)
...
     end
 
+    def on_error(err)
+      case err
+      when CuffSertError
+        @renderer.abort(err)
+      else
+        super(err)
+      end
+      exit(1)
```
Comment (grddev) [inline lib/cuffsert/presenters.rb:87]: In general I don't like calling exit outside "the main function" as it means that the feature composes very badly (and makes it somewhat more difficult to write tests), but maybe it works as intended in this case.

File: lib/cuffsert/rxcfclient.rb [hunk 4]
```diff
@@ -57,8 +58,12 @@ def update_stack(stack_id, change_set_id)
...
         start_time = record_start_time
         @cf.execute_change_set(change_set_name: change_set_id)
-        stack_events(stack_id, start_time) do |event|
-          observer.on_next(event)
+        begin
+          stack_events(stack_id, start_time) do |event|
+            observer.on_next(event)
+          end
+        rescue => e
+          observer.on_error(e)
```
Comment (grddev) [inline lib/cuffsert/rxcfclient.rb:66]: Given that this calls `exit`, this will raise an error that means that `on_completed` will not be called. If that is intentional, I think it would be nicer to stick the on_completed call in an `else` block (or inside the `begin` block depending on the whether errors in the call to `on_completed` can be meaningfully handled using `on_error`.

**Review by grddev — APPROVED** [review]
Looks good overall. It seems a bit iffy to me to use `exit` in (non-top-level) error handling, but it can be changed later if needed.

File: lib/cuffsert/presenters.rb (hunk 3 above)
Comment (bittrance) [reply lib/cuffsert/presenters.rb:87]: I agree. However, Cuffsert uses the "official" RxRuby which has no "await" interface, so the alternative would be to use a mutex or some similar construct to block in `#main` until the presenter is finished. Since there is no indication that RxRuby is maintained, this would have to be a local solution. My experience with `Mutex`, `Queue` and `ConditionalVariable` is somewhat mixed, so in the end I opted for this ugliness.

File: lib/cuffsert/rxcfclient.rb (hunk 4 above)
Comment (bittrance) [reply lib/cuffsert/rxcfclient.rb:66]: Ah, good catch. The Rx contract is to call `on_error` or `on_completed` but not both. RxRuby has some guards that will ensure that `on_completed` will be a no-op in the error case, but you are absolute right that the code should not depend on that. Fixed.
